# Generated by Django 2.0.6 on 2018-12-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20181214_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'exam_grade']},
        ),
    ]
